### ISSUE TITLE
Failed to validate datapack

### ISSUE THREAD

**Issue by hyygybs** [Catscythe-Corner/Seasonals#4]
```
java.util.concurrent.CompletionException: java.lang.NoClassDefFoundError: com/cosmicgelatin/seasonals/core/registry/SeasonalsEffects
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[client-1.19.2-20220805.130853-srg.jar%23926!/:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.19.2-20220805.130853-srg.jar%23926!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[client-1.19.2-20220805.130853-srg.jar%23926!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:116) ~[client-1.19.2-20220805.130853-srg.jar%23926!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1072) ~[client-1.19.2-20220805.130853-srg.jar%23926!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700) ~[client-1.19.2-20220805.130853-srg.jar%23926!/:?]
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23926!/:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23926!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.2.23.jar%2395!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2382!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?]
Caused by: java.lang.NoClassDefFoundError: com/cosmicgelatin/seasonals/core/registry/SeasonalsEffects
	at net.brdle.collectorsreap.compat.SeasonalsCompat.<clinit>(SeasonalsCompat.java:8) ~[collectorsreap-1.19-1.2.3.jar%23607!/:1.2.3]
	at net.brdle.collectorsreap.compat.ModCompat.getFallFlavor(ModCompat.java:65) ~[collectorsreap-1.19-1.2.3.jar%23607!/:1.2.3]
	at net.brdle.collectorsreap.common.item.food.Nutrition.lambda$static$67(Nutrition.java:207) ~[collectorsreap-1.19-1.2.3.jar%23607!/:1.2.3]
	at net.minecraft.world.food.FoodProperties.lambda$getEffects$1(FoodProperties.java:57) ~[client-1.19.2-20220805.130853-srg.jar%23926!/:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
	at net.minecraft.world.food.FoodProperties.m_38749_(FoodProperties.java:57) ~[client-1.19.2-20220805.130853-srg.jar%23926!/:?]
	at cofh.thermal.core.util.managers.dynamo.GourmandFuelManager.getEnergyFromFood(GourmandFuelManager.java:80) ~[thermal_core-1.19.2-10.2.0.5.jar%23980!/:10.2.0.5]
	at cofh.thermal.core.util.managers.dynamo.GourmandFuelManager.getEnergy(GourmandFuelManager.java:63) ~[thermal_core-1.19.2-10.2.0.5.jar%23980!/:10.2.0.5]
	at cofh.thermal.core.util.managers.dynamo.GourmandFuelManager.validFuel(GourmandFuelManager.java:50) ~[thermal_core-1.19.2-10.2.0.5.jar%23980!/:10.2.0.5]
	at cofh.thermal.core.util.managers.dynamo.GourmandFuelManager.createConvertedRecipes(GourmandFuelManager.java:124) ~[thermal_core-1.19.2-10.2.0.5.jar%23980!/:10.2.0.5]
	at cofh.thermal.core.util.managers.dynamo.GourmandFuelManager.refresh(GourmandFuelManager.java:106) ~[thermal_core-1.19.2-10.2.0.5.jar%23980!/:10.2.0.5]
	at cofh.thermal.lib.common.ThermalRecipeManagers.refreshServer(ThermalRecipeManagers.java:52) ~[thermal_core-1.19.2-10.2.0.5.jar%23980!/:10.2.0.5]
	at cofh.thermal.core.event.TCoreCommonSetupEvents.tagsUpdated(TCoreCommonSetupEvents.java:41) ~[thermal_core-1.19.2-10.2.0.5.jar%23980!/:10.2.0.5]
	at cofh.thermal.core.event.__TCoreCommonSetupEvents_tagsUpdated_TagsUpdatedEvent.invoke(.dynamic) ~[thermal_core-1.19.2-10.2.0.5.jar%23980!/:10.2.0.5]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.3.jar%2379!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2379!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2379!/:?]
	at net.minecraft.server.ReloadableServerResources.m_206868_(ReloadableServerResources.java:101) ~[client-1.19.2-20220805.130853-srg.jar%23926!/:?]
	at net.minecraft.server.WorldLoader.m_214372_(WorldLoader.java:35) ~[client-1.19.2-20220805.130853-srg.jar%23926!/:?]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?]
	... 22 more
Caused by: java.lang.ClassNotFoundException: com.cosmicgelatin.seasonals.core.registry.SeasonalsEffects
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:141) ~[securejarhandler-2.1.4.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.brdle.collectorsreap.compat.SeasonalsCompat.<clinit>(SeasonalsCompat.java:8) ~[collectorsreap-1.19-1.2.3.jar%23607!/:1.2.3]
	at net.brdle.collectorsreap.compat.ModCompat.getFallFlavor(ModCompat.java:65) ~[collectorsreap-1.19-1.2.3.jar%23607!/:1.2.3]
	at net.brdle.collectorsreap.common.item.food.Nutrition.lambda$static$67(Nutrition.java:207) ~[collectorsreap-1.19-1.2.3.jar%23607!/:1.2.3]
	at net.minecraft.world.food.FoodProperties.lambda$getEffects$1(FoodProperties.java:57) ~[client-1.19.2-20220805.130853-srg.jar%23926!/:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
	at net.minecraft.world.food.FoodProperties.m_38749_(FoodProperties.java:57) ~[client-1.19.2-20220805.130853-srg.jar%23926!/:?]
	at cofh.thermal.core.util.managers.dynamo.GourmandFuelManager.getEnergyFromFood(GourmandFuelManager.java:80) ~[thermal_core-1.19.2-10.2.0.5.jar%23980!/:10.2.0.5]
	at cofh.thermal.core.util.managers.dynamo.GourmandFuelManager.getEnergy(GourmandFuelManager.java:63) ~[thermal_core-1.19.2-10.2.0.5.jar%23980!/:10.2.0.5]
	at cofh.thermal.core.util.managers.dynamo.GourmandFuelManager.validFuel(GourmandFuelManager.java:50) ~[thermal_core-1.19.2-10.2.0.5.jar%23980!/:10.2.0.5]
	at cofh.thermal.core.util.managers.dynamo.GourmandFuelManager.createConvertedRecipes(GourmandFuelManager.java:124) ~[thermal_core-1.19.2-10.2.0.5.jar%23980!/:10.2.0.5]
	at cofh.thermal.core.util.managers.dynamo.GourmandFuelManager.refresh(GourmandFuelManager.java:106) ~[thermal_core-1.19.2-10.2.0.5.jar%23980!/:10.2.0.5]
	at cofh.thermal.lib.common.ThermalRecipeManagers.refreshServer(ThermalRecipeManagers.java:52) ~[thermal_core-1.19.2-10.2.0.5.jar%23980!/:10.2.0.5]
	at cofh.thermal.core.event.TCoreCommonSetupEvents.tagsUpdated(TCoreCommonSetupEvents.java:41) ~[thermal_core-1.19.2-10.2.0.5.jar%23980!/:10.2.0.5]
	at cofh.thermal.core.event.__TCoreCommonSetupEvents_tagsUpdated_TagsUpdatedEvent.invoke(.dynamic) ~[thermal_core-1.19.2-10.2.0.5.jar%23980!/:10.2.0.5]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.3.jar%2379!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2379!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2379!/:?]
	at net.minecraft.server.ReloadableServerResources.m_206868_(ReloadableServerResources.java:101) ~[client-1.19.2-20220805.130853-srg.jar%23926!/:?]
	at net.minecraft.server.WorldLoader.m_214372_(WorldLoader.java:35) ~[client-1.19.2-20220805.130853-srg.jar%23926!/:?]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?]
	... 22 more
```
version: 1.9.2-4.1.0

**Comment by CodeGiver01** [comment]
Yea I got this too.

**Comment by Uraneptus** [comment]
That's a bug with collectors reap! I have fixed this in a PR on their mod, so you just need to update collectors reap to the newest version!
